'use client';
import {useState} from 'react';
import {Ship,norm} from './domain';
import type {Candidate,EmailPreview} from './email-parser';
type Row=Candidate&{selected:boolean;existingId?:string;status?:string};
export default function EmailImporter({ships,busy,onSave}:{ships:Ship[];busy:boolean;onSave:(rows:Row[])=>void}){
 const [files,setFiles]=useState<EmailPreview[]>([]),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[year,setYear]=useState(new Date().getFullYear());
 function prepare(c:Candidate):Row{const candidates=ships.filter(s=>!s.deleted&&s.status==='Ativo'&&norm(s.name)===norm(c.name));const old=candidates.find(s=>(!c.start||s.end>c.start)&&(!c.end||s.start<c.end));const start=c.start||old?.start||'',end=c.end||old?.end||'';const same=old&&old.start.slice(0,16)===start.slice(0,16)&&old.end.slice(0,16)===end.slice(0,16)&&old.berth===c.berth;const review=c.review.filter(v=>!(start&&v.includes('não informa o início'))&&!(end&&v.includes('não informa o fim')));return {...c,start,end,review,startBasis:start&&c.startBasis==='Início não informado'?'Janela conferida na importação':c.startBasis,existingId:old?.id,selected:!old,status:same?'Já cadastrado — sem alteração':old?'Atualizar operação existente':'Novo navio'};}
 async function upload(list:FileList|null){if(!list?.length)return;setLoading(true);setError('');const results:EmailPreview[]=[];const errors:string[]=[];for(const file of Array.from(list)){try{if(file.size>10000000)throw Error('Limite de 10 MB por arquivo.');const {parseEmail}=await import('./email-parser');const d=await parseEmail(file.name,await file.arrayBuffer(),year);results.push(d);}catch(e){errors.push(file.name+': '+(e as Error).message);}}setFiles(prev=>[...prev,...results]);setRows(prev=>{const next=[...prev];for(const c of results.flatMap(f=>f.ships)){const index=next.findIndex(x=>norm(x.name)===norm(c.name)&&(!x.start||!c.end||x.start<c.end)&&(!x.end||!c.start||x.end>c.start));if(index>=0){const a=next[index];next[index]=prepare({...a,...c,start:c.start||a.start,end:c.end||a.end,source:a.source===c.source?a.source:a.source+' / '+c.source});}else next.push(prepare(c));}return next;});setError(errors.join(' '));setLoading(false);}
 function edit(i:number,key:string,value:unknown){setRows(rows.map((r,j)=>j===i?{...r,[key]:value}:r));}
 const selected=rows.filter(r=>r.selected);
 return <div className="settings-body email-upload">
 <p>Escolha o e-mail salvo no computador. Confira os navios e clique em <strong>Salvar navios selecionados</strong>.</p>
 <label className="field"><span>Ano das datas sem ano no e-mail</span><input aria-label="Ano da programação" type="number" min="2000" max="2100" value={year} onChange={e=>setYear(Number(e.target.value))}/></label>
 <label className="upload-zone"><strong>{loading?'Lendo arquivo…':'Selecionar e-mail ou Berthing Plan'}</strong><span>Outlook .msg, .eml ou imagem .png/.jpg · até 10 MB por arquivo · pode selecionar vários arquivos juntos</span><input aria-label="Arquivo de e-mail" type="file" accept=".msg,.eml,.png,.jpg,.jpeg,.webp" multiple disabled={loading||busy} onChange={e=>{upload(e.target.files);e.target.value='';}}/></label>
 {error&&<p className="alert danger" role="alert">{error}</p>}
 {files.map((f,i)=><details key={i}><summary>{f.file} · {f.ships.length} navios identificados</summary><p className="review-flag">{f.notice}</p>{f.images.map((a,j)=><figure key={j}><figcaption>{a.name}</figcaption><a href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.name} style={{maxWidth:'100%'}}/></a></figure>)}<pre className="email-text">{f.text}</pre></details>)}
 {!!files.length&&<><h3>Confira antes de importar</h3><p className="meta">Os navios já cadastrados ficam desmarcados. Marque uma operação existente somente se desejar atualizar os horários. Nada é salvo até clicar no botão abaixo.</p>
 <form onSubmit={e=>{e.preventDefault();setError('');if(!selected.length){setError('Selecione pelo menos um navio.');return;}if(selected.some(r=>!r.name.trim()||!r.berth.trim()||!r.start||!r.end||r.end<=r.start)){setError('Complete nome, berço, início e fim de todos os navios selecionados. O fim deve ser posterior ao início.');return;}onSave(selected);}}>
 {rows.map((r,i)=><section className="import-edit-row" key={i}><label className="check"><input type="checkbox" checked={r.selected} onChange={e=>edit(i,'selected',e.target.checked)}/><strong>{r.name||'Novo navio'}</strong> · {r.status}</label>{r.existingId&&<p className="meta">Cadastro atual: {ships.find(v=>v.id===r.existingId)?.start.replace('T',' ')} até {ships.find(v=>v.id===r.existingId)?.end.replace('T',' ')}</p>}<div className="form-grid"><label className="field"><span>Nome</span><input aria-label={`Navio ${i+1} nome`} value={r.name} onChange={e=>edit(i,'name',e.target.value)}/></label><label className="field"><span>Berço</span><input aria-label={`Navio ${i+1} berço`} value={r.berth} onChange={e=>edit(i,'berth',e.target.value)}/></label><label className="field"><span>Início da operação</span><input aria-label={`Navio ${i+1} início`} type="datetime-local" value={r.start.slice(0,16)} onChange={e=>edit(i,'start',e.target.value)}/></label><label className="field"><span>Fim previsto</span><input aria-label={`Navio ${i+1} fim`} type="datetime-local" value={r.end.slice(0,16)} onChange={e=>edit(i,'end',e.target.value)}/></label></div>{r.review.map((v,j)=><small className="review-flag" key={j}>{v}</small>)}</section>)}
 <button type="button" onClick={()=>setRows([...rows,{name:'',berth:'',start:'',end:'',source:files.map(f=>f.subject).join(' / '),note:'Preenchido durante importação de e-mail',startBasis:'Revisão manual',review:[],selected:true,status:'Novo navio'}])}>+ Adicionar navio do anexo</button>
 <div className="modal-actions"><span>{selected.length} selecionado(s)</span><button className="primary" disabled={busy||loading||!selected.length}>Salvar navios selecionados</button></div>
 </form></>}
 </div>;
}

