'use client';
import {useMemo,useState} from 'react';
import {adherenceSeries,dayObligations} from './analytics';
import {TYPES,periodsFor,score,fmtDate,fmtTime,shiftDate,type State,type Obligation} from './domain';
type Props={state:State;date:string;now:number};
const pct=(k:{total:number;pct:number})=>k.total?k.pct+'%':'—';
function Metric({label,value,note,tone=''}:{label:string;value:string|number;note:string;tone?:string}){return <article className={'op-metric '+tone}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>}
export function AdherenceView({state,date,now}:Props){
 const [mode,setMode]=useState<'week'|'month'>('week'),[type,setType]=useState('Todos');
 const series=useMemo(()=>adherenceSeries(state,date,mode,now,type),[state,date,mode,now,type]);
 const rows=series.flatMap(x=>x.rows),k=score(rows);const missed=rows.filter(r=>r.status==='Atrasado').length;
 const max=series.length===7?'seven':'month';
 return <div className="analytics-view"><div className="analytics-controls"><div className="tabs" aria-label="Intervalo do gráfico"><button className={mode==='week'?'selected':''} onClick={()=>setMode('week')}>Semana</button><button className={mode==='month'?'selected':''} onClick={()=>setMode('month')}>Mês</button></div><strong>{fmtDate(series[0].date)} — {fmtDate(series[series.length-1].date)}</strong><select aria-label="Equipe do gráfico" value={type} onChange={e=>setType(e.target.value)}>{['Todos',...TYPES].map(t=><option key={t}>{t}</option>)}</select></div>
 <div className="op-metrics"><Metric label="ADERÊNCIA ACUMULADA" value={pct(k)} note="Realizados ÷ esperados até agora"/><Metric label="DDS REALIZADOS" value={k.done} note={`de ${k.total} esperados`}/><Metric label="ATRASADOS" value={missed} note="Sem DDS após o prazo" tone={missed?'attention':''}/><Metric label="COM PENDÊNCIA" value={rows.filter(r=>r.status==='Realizado com pendência').length} note="DDS realizado, documentação incompleta"/></div>
 <section className="panel"><div className="panel-head"><h2>{mode==='week'?'Evolução da semana':'Evolução do mês'}</h2><span className="meta">Percentual por dia · {type==='Todos'?'todas as equipes':type}</span></div><div className="trend-scroll"><div className={'trend-chart '+max} role="img" aria-label="Aderência diária. Valores detalhados disponíveis na tabela abaixo.">{series.map(p=><div className="trend-day" key={p.date} title={`${fmtDate(p.date)}: ${p.done}/${p.total} DDS (${pct(p)})`}><strong>{pct(p)}</strong><div className="trend-track"><i style={{height:(p.total?Math.max(p.pct,1):0)+'%'}}/></div><span>{mode==='week'?new Intl.DateTimeFormat('pt-BR',{weekday:'short',timeZone:'UTC'}).format(new Date(p.date+'T12:00:00Z')):p.date.slice(8)}</span>{mode==='week'&&<small>{p.date.slice(8)}/{p.date.slice(5,7)}</small>}</div>)}</div></div><div className="chart-note">— Sem obrigações iniciadas. Dias futuros não entram no cálculo. Barras em 0% indicam obrigações sem DDS realizado.</div></section>
 <section className="panel"><div className="panel-head"><h2>Aderência por função</h2><span className="meta">Mesmo intervalo selecionado</span></div><div className="team-bars">{TYPES.filter(t=>type==='Todos'||t===type).map(t=>{const v=score(rows.filter(r=>r.type===t));return <div key={t}><strong>{t}</strong><div className="track"><i style={{width:v.pct+'%'}}/></div><span>{pct(v)}</span><small>{v.done}/{v.total} DDS</small></div>})}</div></section>
 <details className="panel analytics-details"><summary>Ver números por dia</summary><div className="table-wrap"><table><thead><tr><th>Dia</th><th>Realizados</th><th>Esperados</th><th>Aderência</th></tr></thead><tbody>{series.map(p=><tr key={p.date}><td>{fmtDate(p.date)}</td><td>{p.done}</td><td>{p.total}</td><td>{pct(p)}</td></tr>)}</tbody></table></div></details><p className="footnote">Cálculo com os registros disponíveis e as regras atuais. Inclui realizados com pendência; justificativas não contam como DDS. A ausência de importações antigas pode reduzir os resultados históricos.</p></div>;
}
export function DayDashboard({state,date,now,onOpen,onPeriod}:Props&{onOpen:(r:Obligation)=>void;onPeriod:(i:number)=>void}){
 const all=dayObligations(state,date,now),started=all.filter(r=>r.start<=now),k=score(started);
 const late=started.filter(r=>r.status==='Atrasado'),incomplete=started.filter(r=>r.status==='Realizado com pendência');
 const periods=periodsFor(state.settings);const priorities=[...late,...started.filter(r=>r.status==='Aguardando'),...incomplete].sort((a,b)=>({Atrasado:0,Aguardando:1,'Realizado com pendência':2} as any)[a.status]-({Atrasado:0,Aguardando:1,'Realizado com pendência':2} as any)[b.status]||a.due-b.due);
 const trend=Array.from({length:7},(_,i)=>{const d=shiftDate(date,i-6);return {date:d,...score(dayObligations(state,d,now).filter(r=>r.start<=now))};});
 return <div className="day-board"><div className="op-metrics"><Metric label="ADERÊNCIA ATÉ AGORA" value={pct(k)} note={`${k.done} de ${k.total} DDS iniciados`}/><Metric label="ATRASADOS" value={late.length} note="Prioridade de atendimento" tone={late.length?'attention':''}/><Metric label="COM PENDÊNCIA" value={incomplete.length} note="Conferir documentação"/><Metric label="PRÓXIMOS DDS" value={all.filter(r=>r.start>now).length} note="Previstos para os próximos períodos"/></div>
 <div className="day-teams">{TYPES.map(t=>{const v=score(started.filter(r=>r.type===t));return <article key={t}><span>{t}</span><strong>{pct(v)}</strong><div className="track"><i style={{width:v.pct+'%'}}/></div><small>{v.done}/{v.total} realizados</small></article>})}</div>
 <div className="board-grid"><section className="panel"><div className="panel-head"><h2>Mapa do dia</h2><span className="meta">Realizados / previstos · clique para abrir</span></div><div className="table-wrap matrix"><table><thead><tr><th>Função</th>{periods.map((p,i)=><th key={i}>{p}</th>)}</tr></thead><tbody>{TYPES.map(t=><tr key={t}><td><strong>{t}</strong></td>{periods.map((p,i)=>{const group=all.filter(r=>r.type===t&&r.period===p);const v=score(group);const tone=group.some(r=>r.status==='Atrasado')?'late':group.some(r=>r.status==='Realizado com pendência')?'partial':group.length&&group.every(r=>r.record)?'done':group.some(r=>r.start<=now)?'waiting':'';return <td key={i}>{v.total?<button className={'matrix-cell '+tone} onClick={()=>onPeriod(i)} aria-label={`${t}, ${p}, ${v.done} de ${v.total} realizados`}>{v.done}/{v.total}</button>:<span className="meta">—</span>}</td>})}</tr>)}</tbody></table></div><div className="matrix-legend"><span>● Realizado</span><span>● Atrasado</span><span>● Aguardando / incompleto</span><span>○ Próximo período</span></div></section>
 <section className="panel priority-panel"><div className="panel-head"><h2>Prioridades</h2><span className="meta">{priorities.length} itens</span></div><div className="priority-list">{priorities.slice(0,4).map(r=><button key={r.key} onClick={()=>onOpen(r)}><span><strong>{r.reference}</strong><small>{r.period} · prazo {fmtTime(r.due)}</small></span><span className={r.status==='Atrasado'?'priority-late':''}>{r.status}</span></button>)}{!priorities.length&&<div className="empty compact">Nenhum atraso ou pendência até agora.</div>}{priorities.length>4&&<small>Mostrando 4 de {priorities.length}. Abra o período no mapa para ver os demais.</small>}</div><div className="mini-trend"><h3>Últimos 7 dias</h3><div>{trend.map(p=><span key={p.date} title={`${fmtDate(p.date)}: ${pct(p)} (${p.done}/${p.total})`}><b>{pct(p)}</b><i style={{height:Math.max(p.total?p.pct*.45:0,2)}}/><small>{p.date.slice(8)}/{p.date.slice(5,7)}</small></span>)}</div></div></section></div>
 <p className="board-note">Indicadores consideram obrigações iniciadas. O mapa inclui a programação completa do dia.</p></div>;
}
