'use client';
import {useState} from 'react';
import {Settings,TYPES,config,parsePeriod,validateSettings} from './domain';
export default function RulesEditor({settings,busy,onSave}:{settings:Settings;busy:boolean;onSave:(s:Settings)=>void}){
 const [draft,setDraft]=useState(()=>({...settings,...config(settings)})),[error,setError]=useState('');
 const time=(n:number)=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
 function changePeriod(group:'core'|'support',i:number,side:number,value:string){const pair=draft[group][i].split('–');pair[side]=value;setDraft({...draft,[group]:draft[group].map((p,j)=>j===i?pair.join('–'):p)});}
 return <form className="settings-body rules-editor" onSubmit={e=>{e.preventDefault();try{setError('');onSave(validateSettings(draft));}catch(e){setError((e as Error).message);}}}>
 <h3>Quantidade de DDS por período</h3><p className="meta">NAVIO: quantidade por navio ativo. Demais equipes: quantidade por equipe. Use zero para desativar a cobrança.</p>
 <div className="table-wrap"><table><thead><tr><th>Equipe</th><th>DDS esperados</th><th>Horários utilizados</th></tr></thead><tbody>{TYPES.map(t=><tr key={t}><td><strong>{t}</strong></td><td><input aria-label={'Quantidade de DDS '+t} type="number" min="0" max="20" required value={draft.rules[t].quantity} onChange={e=>setDraft({...draft,rules:{...draft.rules,[t]:{...draft.rules[t],quantity:Number(e.target.value)}}})}/></td><td><select aria-label={'Horários de '+t} value={t==='NAVIO'?'core':draft.rules[t].group} disabled={t==='NAVIO'} onChange={e=>setDraft({...draft,rules:{...draft.rules,[t]:{...draft.rules[t],group:e.target.value as 'core'|'support'}}})}><option value="core">Horários principais</option><option value="support">Turnos de apoio</option></select></td></tr>)}</tbody></table></div>
 <div className="schedule-grid">{(['core','support'] as const).map((group,g)=><section key={group}><h3>{TYPES.filter(t=>draft.rules[t].group===group).join(' · ')||'Sem equipes'}</h3><p className="meta">Períodos utilizados por estas funções</p>{draft[group].map((p,i)=>{let pair=p.split('–').map(v=>v.length===2?v+':00':v);return <div className="schedule-row" key={i}><label>Início<input aria-label={`Período ${i+1} início`} type="time" required value={pair[0]} onChange={e=>changePeriod(group,i,0,e.target.value)}/></label><label>Fim<input aria-label={`Período ${i+1} fim`} type="time" required value={pair[1]} onChange={e=>changePeriod(group,i,1,e.target.value)}/></label><button type="button" aria-label={`Remover período ${i+1} este grupo`} disabled={draft[group].length===1} onClick={()=>setDraft({...draft,[group]:draft[group].filter((_,j)=>j!==i)})}>Remover</button></div>})}<button type="button" disabled={draft[group].length>=12} onClick={()=>setDraft({...draft,[group]:[...draft[group],'00:00–01:00']})}>+ Adicionar período</button></section>)}</div>
 <p className="meta">Cada grupo deve cobrir as 24 horas, sem sobreposição. Quando o fim é menor que o início, o período termina no dia seguinte.</p>
 <label className="field"><span>Tolerância (minutos)</span><input type="number" min="0" max="360" required value={draft.tolerance} onChange={e=>setDraft({...draft,tolerance:Number(e.target.value)})}/></label>
 <label className="check"><input type="checkbox" checked={draft.requirePhoto} onChange={e=>setDraft({...draft,requirePhoto:e.target.checked})}/> Exigir foto</label><label className="check"><input type="checkbox" checked={draft.requireSignature} onChange={e=>setDraft({...draft,requireSignature:e.target.checked})}/> Exigir assinatura</label>
 <p className="review-flag">Ao salvar, os indicadores serão recalculados com estas regras, inclusive nas datas anteriores. Os registros de DDS serão preservados; horários que deixarem de existir precisarão de revisão.</p>
 {error&&<p role="alert" className="alert danger">{error}</p>}<button className="primary" disabled={busy}>Salvar configurações</button>
 </form>;
}
